apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "naveen-portfolio.fullname" . }}
  labels:
    app: {{ include "naveen-portfolio.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "naveen-portfolio.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "naveen-portfolio.name" . }}
    spec:
      containers:
        - name: {{ include "naveen-portfolio.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "naveen-portfolio.fullname" . }}-secret
                  key: MAIL_USER
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "naveen-portfolio.fullname" . }}-secret
                  key: MAIL_PASS
          resources:
{{ toYaml .Values.resources | indent 12 }}
